# Generated by Django 5.1.6 on 2026-03-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0002_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Se True, il commento è nascosto dalle risposte API (moderazione)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp_second',
            field=models.PositiveIntegerField(default=0, help_text='Secondo del video a cui si riferisce il commento (>=0, <= durata video)'),
        ),
    ]
