# Generated by Django 5.1.6 on 2026-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0003_comment_is_disabled_alter_comment_timestamp_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text="Biografia dell'utente"),
        ),
    ]
