# Generated by Django 5.1.6 on 2025-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0003_contest_video_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
