# Generated by Django 5.1.6 on 2026-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0004_add_bio_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='Consenti il download della clip ad altri utenti'),
        ),
    ]
