# Generated by Django 5.1.6 on 2025-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0004_contest_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
