# Generated by Django 5.1.6 on 2026-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0005_add_allow_download_to_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail auto-generato dal primo frame del video', null=True, upload_to='thumbnails/'),
        ),
    ]
