# Generated by Django 5.1.6 on 2026-03-08 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0006_add_thumbnail_to_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora del like')),
                ('comment', models.ForeignKey(help_text='Commento che ha ricevuto il like', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cs_clips.comment')),
                ('user', models.ForeignKey(help_text='Utente che ha messo like al commento', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like commento',
                'verbose_name_plural': 'Like commento',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora del like')),
                ('user', models.ForeignKey(help_text='Utente che ha messo like al video', on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(help_text='Video che ha ricevuto il like', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cs_clips.video')),
            ],
            options={
                'verbose_name': 'Like video',
                'verbose_name_plural': 'Like video',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
