# Generated by Django 5.1.6 on 2026-03-08 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0007_commentlike_videolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment_received', 'Commento ricevuto'), ('like_received', 'Like ricevuto'), ('comment_promoted', 'Commento promosso a popup'), ('contest_opened', 'Nuovo contest aperto'), ('bracket_invite', 'Invito bracket'), ('bracket_turn', 'Turno bracket disponibile'), ('contest_results', 'Risultati contest')], help_text='Tipo di notifica', max_length=30)),
                ('is_read', models.BooleanField(default=False, help_text='Se la notifica è stata letta')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione')),
                ('comment', models.ForeignKey(blank=True, help_text='Commento collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cs_clips.comment')),
                ('contest', models.ForeignKey(blank=True, help_text='Contest collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cs_clips.contest')),
                ('recipient', models.ForeignKey(help_text='Utente che riceve la notifica', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text="Utente che ha generato l'evento (null per eventi di sistema)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text='Video collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cs_clips.video')),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date'), models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read')],
            },
        ),
    ]
