# Generated by Django 5.1.6 on 2026-03-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Commento collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cs_clips.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='contest',
            field=models.ForeignKey(blank=True, help_text='Contest collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cs_clips.contest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Video collegato alla notifica (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cs_clips.video'),
        ),
    ]
