# Generated by Django 5.1.6 on 2026-03-08 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0009_notification_set_null_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome del torneo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrizione del torneo')),
                ('status', models.CharField(choices=[('registration', 'Registrazione aperta'), ('active', 'Torneo in corso'), ('completed', 'Torneo completato')], default='registration', help_text='Stato attuale del torneo', max_length=20)),
                ('max_participants', models.PositiveIntegerField(help_text='Numero massimo di partecipanti')),
                ('current_round', models.PositiveIntegerField(default=1, help_text='Turno attuale del torneo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione')),
                ('prize_description', models.TextField(blank=True, help_text='Descrizione del premio per il vincitore')),
                ('created_by', models.ForeignKey(help_text='Admin che ha creato il torneo', on_delete=django.db.models.deletion.CASCADE, related_name='created_brackets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bracket',
                'verbose_name_plural': 'Bracket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di iscrizione')),
                ('bracket', models.ForeignKey(help_text="Torneo a cui l'utente si iscrive", on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cs_clips.bracket')),
                ('user', models.ForeignKey(help_text='Utente iscritto al torneo', on_delete=django.db.models.deletion.CASCADE, related_name='bracket_entries', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(help_text='Video presentato per il torneo', on_delete=django.db.models.deletion.CASCADE, related_name='bracket_entries', to='cs_clips.video')),
            ],
            options={
                'verbose_name': 'Iscrizione torneo',
                'verbose_name_plural': 'Iscrizioni torneo',
                'ordering': ['-created_at'],
                'unique_together': {('bracket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Numero del turno (1 = primo turno)')),
                ('position', models.PositiveIntegerField(help_text='Posizione del matchup nel turno')),
                ('is_completed', models.BooleanField(default=False, help_text="Indica se il matchup e' stato completato")),
                ('bracket', models.ForeignKey(help_text='Torneo a cui appartiene il matchup', on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='cs_clips.bracket')),
                ('entry_1', models.ForeignKey(blank=True, help_text='Primo partecipante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_as_entry1', to='cs_clips.contestentry')),
                ('entry_2', models.ForeignKey(blank=True, help_text='Secondo partecipante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_as_entry2', to='cs_clips.contestentry')),
                ('winner', models.ForeignKey(blank=True, help_text='Vincitore del matchup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_won', to='cs_clips.contestentry')),
            ],
            options={
                'verbose_name': 'Matchup',
                'verbose_name_plural': 'Matchup',
                'ordering': ['round_number', 'position'],
                'unique_together': {('bracket', 'round_number', 'position')},
            },
        ),
    ]
