# Generated by Django 5.1.6 on 2026-03-15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cs_clips", "0010_bracket_contestentry_matchup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchupVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        help_text="Voto da 1 a 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e ora del voto",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="Entry votata dall'utente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_votes",
                        to="cs_clips.contestentry",
                    ),
                ),
                (
                    "matchup",
                    models.ForeignKey(
                        help_text="Matchup votato",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="cs_clips.matchup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utente che ha votato",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchup_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto matchup",
                "verbose_name_plural": "Voti matchup",
                "ordering": ["-created_at"],
                "unique_together": {("matchup", "user")},
            },
        ),
    ]
