# Generated by Django 5.1.6 on 2025-06-16 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0012_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp_second',
            field=models.PositiveIntegerField(default=0, help_text='Secondo del video a cui si riferisce il commento (>=1, <= durata video))'),
        ),
        migrations.AddField(
            model_name='contest',
            name='tag',
            field=models.CharField(choices=[('clutch', 'Clutch'), ('funny', 'Funny'), ('fail', 'Fail')], default='funny', help_text='Tag che identifica la categoria del contest', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Durata del video in secondi'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.CharField(choices=[('clutch', 'Clutch'), ('funny', 'Funny'), ('fail', 'Fail')], default='funny', help_text='Tag del video, deve corrispondere al contest', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together={('start_date', 'end_date', 'tag')},
        ),
    ]
