# Generated by Django 5.1.6 on 2026-02-14 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0014_user_following_alter_comment_timestamp_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Commento disabilitato (soft-delete per moderazione)'),
        ),
        migrations.AddField(
            model_name='video',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='Consente il download del video'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment', 'Commento ricevuto'), ('comment_like', 'Like al commento'), ('video_like', 'Like alla clip'), ('popup_promoted', 'Commento promosso a popup'), ('contest_invite', 'Invito contest'), ('contest_turn', 'Turno contest disponibile')], help_text='Tipo di notifica', max_length=30)),
                ('content', models.TextField(help_text='Testo della notifica')),
                ('related_object_id', models.PositiveIntegerField(help_text="ID dell'oggetto correlato (risolto dal frontend in base al type)")),
                ('read', models.BooleanField(default=False, help_text='Se la notifica è stata letta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cs_clips.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cs_clips.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
