# Generated by Django 5.1.6 on 2026-02-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0016_create_moderator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text="Breve descrizione dell'utente", max_length=500),
        ),
    ]
