# Generated by Django 5.1.6 on 2025-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
    ]
