# Generated by Django 5.1.6 on 2025-06-03 08:28

from django.db import migrations

def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ['toconfirm', 'user', 'admin']:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0001_initial'),  # Cambia con la tua initial migration
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
