# Generated by Django 5.1.6 on 2025-06-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0006_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to='cs_clips.video'),
        ),
    ]
