# Generated by Django 5.1.6 on 2025-06-17 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_clips', '0013_comment_timestamp_second_contest_tag_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Utenti che questo utente sta seguendo', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp_second',
            field=models.PositiveIntegerField(default=0, help_text='Secondo del video a cui si riferisce il commento (>=0, <= durata video))'),
        ),
    ]
